export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILED = 'GET_POST_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const LOGIN_MODAL = 'LOGIN_MODAL';
export const SIGN_UP_MODAL = 'SIGN_UP_MODAL';
export const GET_RECEIVED_AUTH = 'GET_RECEIVED_AUTH';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_USER_REQUESTED_BY_ID = 'GET_USER_REQUESTED_BY_ID';
export const GET_USER_REQUEST_BY_TOKEN = 'GET_USER_REQUEST_BY_TOKEN';
export const GET_RECEIVED_USER = 'GET_RECEIVED_USER';
export const GET_FAILED_USER = 'GET_FAILED_USER';
